export enum Expansions {
  PHANTASMAL_FLAMES = 'Phantasmal Flames',
  MEGA_EVOLUTION = 'Mega Evolution',
  MEGA_EVOLUTION_PROMOS = 'Mega Evolution Promos',

  SCARLET_AND_VIOLET_PROMOS = "Scarlet & Violet Promos",
  SCARLET_AND_VIOLET = "Scarlet & Violet",
  PALDEA_EVOLVED = "Paldea Evolved",
  OBSIDIAN_FLAMES = "Obsidian Flames",
  SCARLET_AND_VIOLET_151 = "Scarlet & Violet 151",
  PARADOX_RIFT = "Paradox Rift",
  TEMPORAL_FORCES = "Temporal Forces",
  PALDEAN_FATES = "Paldean Fates",
  TWILIGHT_MASQUERADE = "Twilight Masquerade",
  SHROUDED_FABLE = "Shrouded Fable",
  STELLAR_CROWN = "Stellar Crown",
  PRISMATIC_EVOLUTIONS = "Prismatic Evolutions",
  SURGING_SPARKS = "Surging Sparks",
  JOURNEY_TOGETHER = "Journey Together",
  DESTINED_RIVALS = "Destined Rivals",
  WHITE_FLARE = "White Flare",
  BLACK_BOLT = "Black Bolt",

  CROWN_ZENITH = "Crown Zenith",
  SILVER_TEMPEST = "Silver Tempest",
  LOST_ORIGIN = "Lost Origin",
  POKEMON_GO = "Pokémon GO",
  ASTRAL_RADIANCE = "Astral Radiance",
  BRILLIANT_STARS = "Brilliant Stars",
  FUSION_STRIKE = "Fusion Strike",
  CELEBRATIONS = "Celebrations",
  EVOLVING_SKIES = "Evolving Skies",
  CHILLING_REIGN = "Chilling Reign",
  BATTLE_STYLES = "Battle Styles",
  SHINING_FATES = "Shining Fates",
  VIVID_VOLTAGE = "Vivid Voltage",
  CHAMPIONS_PATH = "Champion's Path",
  DARKNESS_ABLAZE = "Darkness Ablaze",
  REBEL_CLASH = "Rebel Clash",
  SWORD_AND_SHIELD = "Sword & Shield",
  SWORD_AND_SHIELD_PROMOS = "Sword & Shield Promos",

  COSMIC_ECLIPSE = "Cosmic Eclipse",
  CRIMSON_INVASION = "Crimson Invasion",
  BURNING_SHADOWS = "Burning Shadows",
  GUARDIANS_RISING = "Guardians Rising",
  SUN_AND_MOON = "Sun & Moon",
  SUN_AND_MOON_PROMOS = "Sun & Moon Promos",

  STEAM_SIEGE = "Steam Siege",
  ROARING_SKIES = "Roaring Skies",
  XY_PROMOS = "XY Promos",
}

export const ExpansionsInSDK = {
  [Expansions.PHANTASMAL_FLAMES]: 'me2',
  [Expansions.MEGA_EVOLUTION]: 'me1',
  [Expansions.MEGA_EVOLUTION_PROMOS]: 'mep',

  // SV
  [Expansions.SCARLET_AND_VIOLET_PROMOS]: "svp",
  [Expansions.SCARLET_AND_VIOLET]: "sv1",
  [Expansions.PALDEA_EVOLVED]: "sv2",
  [Expansions.OBSIDIAN_FLAMES]: "sv3",
  [Expansions.SCARLET_AND_VIOLET_151]: "sv3pt5",
  [Expansions.PARADOX_RIFT]: "sv4",
  [Expansions.TEMPORAL_FORCES]: "sv5",
  [Expansions.PALDEAN_FATES]: "sv4pt5",
  [Expansions.TWILIGHT_MASQUERADE]: "sv6",
  [Expansions.SHROUDED_FABLE]: "sv6pt5",
  [Expansions.STELLAR_CROWN]: "sv7",
  [Expansions.PRISMATIC_EVOLUTIONS]: "sv8pt5",
  [Expansions.SURGING_SPARKS]: "sv8",
  [Expansions.JOURNEY_TOGETHER]: "sv9",
  [Expansions.DESTINED_RIVALS]: "sv10",
  [Expansions.WHITE_FLARE]: "rsv10pt5",
  [Expansions.BLACK_BOLT]: "zsv10pt5",
  // // SWSH
  [Expansions.CROWN_ZENITH]: "swsh12pt5",
  [Expansions.REBEL_CLASH]: "swsh2",
  [Expansions.POKEMON_GO]: "pgo",
  [Expansions.CELEBRATIONS]: "cel25",
  [Expansions.VIVID_VOLTAGE]: "swsh4",
  [Expansions.SHINING_FATES]: "swsh45",
  [Expansions.BATTLE_STYLES]: "swsh5",
  [Expansions.CHILLING_REIGN]: "swsh6",
  [Expansions.EVOLVING_SKIES]: "swsh7",
  [Expansions.FUSION_STRIKE]: "swsh8",
  [Expansions.BRILLIANT_STARS]: "swsh9",
  [Expansions.ASTRAL_RADIANCE]: "swsh10",
  [Expansions.LOST_ORIGIN]: "swsh11",
  [Expansions.SILVER_TEMPEST]: "swsh12",
  [Expansions.CHAMPIONS_PATH]: "swsh35",
  [Expansions.DARKNESS_ABLAZE]: "swsh3",
  [Expansions.SWORD_AND_SHIELD]: "swsh1",
  [Expansions.SWORD_AND_SHIELD_PROMOS]: "swshp",
  [Expansions.COSMIC_ECLIPSE]: "sm12",
  [Expansions.CRIMSON_INVASION]: "sm4",
  [Expansions.BURNING_SHADOWS]: "sm3",
  [Expansions.GUARDIANS_RISING]: "sm2",
  [Expansions.SUN_AND_MOON]: "det1",
  [Expansions.SUN_AND_MOON_PROMOS]: "smp",
  [Expansions.STEAM_SIEGE]: "xy11",
  [Expansions.ROARING_SKIES]: "xy6",
  [Expansions.XY_PROMOS]: "xyp",
};

export const ExpansionsShortName = {
  [Expansions.PHANTASMAL_FLAMES]: 'PFL',
  [Expansions.MEGA_EVOLUTION]: 'MEG',
  [Expansions.MEGA_EVOLUTION_PROMOS]: 'MEP',

  [Expansions.SCARLET_AND_VIOLET_PROMOS]: "SVP",
  [Expansions.SCARLET_AND_VIOLET]: "SVI",
  [Expansions.PALDEA_EVOLVED]: "PAL",
  [Expansions.OBSIDIAN_FLAMES]: "OBF",
  [Expansions.SCARLET_AND_VIOLET_151]: "MEW",
  [Expansions.PARADOX_RIFT]: "PAR",
  [Expansions.TEMPORAL_FORCES]: "TEF",
  [Expansions.PALDEAN_FATES]: "PAF",
  [Expansions.TWILIGHT_MASQUERADE]: "TWM",
  [Expansions.SHROUDED_FABLE]: "SFA",
  [Expansions.STELLAR_CROWN]: "SCR",
  [Expansions.PRISMATIC_EVOLUTIONS]: "PRE",
  [Expansions.SURGING_SPARKS]: "SSP",
  [Expansions.JOURNEY_TOGETHER]: "JTG",
  [Expansions.DESTINED_RIVALS]: "DRI",
  [Expansions.WHITE_FLARE]: "WHT",
  [Expansions.BLACK_BOLT]: "BLK",
  // // SWSH
  [Expansions.CROWN_ZENITH]: "CRZ",
  [Expansions.REBEL_CLASH]: "RCL",
  [Expansions.POKEMON_GO]: "PGO",
  [Expansions.CELEBRATIONS]: "CEL",
  [Expansions.VIVID_VOLTAGE]: "VIV",
  [Expansions.SHINING_FATES]: "SHF",
  [Expansions.BATTLE_STYLES]: "BST",
  [Expansions.CHILLING_REIGN]: "CRE",
  [Expansions.EVOLVING_SKIES]: "EVS",
  [Expansions.FUSION_STRIKE]: "FST",
  [Expansions.BRILLIANT_STARS]: "BRS",
  [Expansions.ASTRAL_RADIANCE]: "ASR",
  [Expansions.LOST_ORIGIN]: "LOR",
  [Expansions.SILVER_TEMPEST]: "SIT",
  [Expansions.CHAMPIONS_PATH]: "CPA",
  [Expansions.DARKNESS_ABLAZE]: "DAA",
  [Expansions.SWORD_AND_SHIELD]: "SSH",
  [Expansions.SWORD_AND_SHIELD_PROMOS]: "SSP",
  [Expansions.COSMIC_ECLIPSE]: "CES",
  [Expansions.CRIMSON_INVASION]: "CIN",
  [Expansions.BURNING_SHADOWS]: "BUS",
  [Expansions.GUARDIANS_RISING]: "GRI",
  [Expansions.SUN_AND_MOON]: "SUM",
  [Expansions.SUN_AND_MOON_PROMOS]: "SMP",
  [Expansions.STEAM_SIEGE]: "STS",
  [Expansions.ROARING_SKIES]: "ROS",
  [Expansions.XY_PROMOS]: "XYP",
};
